### PR TITLE
Changed from cu to CuArray the way to create arrays in GPU memory.

### PR DESCRIPTION
**Pull request by b-fg**
`cu` converts the array element type to Float32, regardless of the original array element type. `CuArray` maintains the original array element type. All tests passing.

### CODE REVIEW

**Comment by weymouth** [comment]
What does this do in practice? Is it faster or more stable than using `cu`?

**Comment by b-fg** [comment]
It is consequent to the user decision to work on single or double precision. Previously, even if `T=Float64` was passed to `Flow`, the fields would store `Float32` arrays if `f=cu` was also passed.

**Comment by weymouth** [comment]
Ah. Yes, I did see that earlier. Of course, we should recommend people run Float32 right?

**Comment by b-fg** [comment]
Indeed, but it is still good to have both things working properly ;)

**Pull request merged**
