### PR TITLE
Adding Polyester package for CPU backend and improving allocations

### PR DESCRIPTION
**Pull request by b-fg**

### CODE REVIEW

**Comment by b-fg** [comment]
Actually, KA is faster than Polyester even if allocating much more.

**Comment by b-fg** [comment]
I have seen that one of the allocating lines is this one:
https://github.com/weymouth/WaterLily.jl/blob/33421ae7b53143c58c7741aced9461fecca44fc4/src/Poisson.jl#L126
which can be easily improved with `@views` for a CPU backend, but then the GPU complains. Maybe we could just write a kernel instead of borrowing the dot product operator from LinearAlgebra.

**Comment by weymouth** [comment]
Is this needed after #129 ?

**Comment by b-fg** [comment]
Nope :) Closing thanks to https://github.com/weymouth/WaterLily.jl/pull/129.

**Pull request closed without merging**
