### PR TITLE
Remove useless dependencies from Project.toml

### PR DESCRIPTION
**Pull request by giordano**
Unless I'm missing something, `Documenter` and `Test` aren't used in the package itself.

### CODE REVIEW

**Comment by b-fg** [comment]
Thanks for the PR :) CI uses `Documenter` to build the docs, and this is why tests are failing now. Maybe there is a better way to do this? Also, note that I am in the middle of transitioning to package extensions in https://github.com/weymouth/WaterLily.jl/pull/98 but this partial cleanup is also welcomed in the meantime. Thanks!

**Comment by giordano** [comment]
Documenter is already in https://github.com/weymouth/WaterLily.jl/blob/57671f80c584c74b614b41b2c275f0a396a1c54f/docs/Project.toml#L2 why does the package itself require Documenter?

**Comment by giordano** [comment]
The only problem was that in my first commit I didn't remove the compat entry of `Documenter`.

**Comment by b-fg** [comment]
Ah I see! Thanks :)

**Pull request merged**
